apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-mcp
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/instance: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/dialvare/sample-app-mcp'
    targetRevision: main
    path: overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: git-mcp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
